### ISSUE TITLE
SAP6 URL issue in README

### ISSUE THREAD

**Issue by romainreignier** [furbrain/CircuitPython_CaveBLE#1]
Hi @furbrain 
After seeing signs of a new SAP device, the SAP6, in the TopoDroid and SexyTopo logs, I have found this repo.
But the link in the README seems to be missing the `www.` part because the link points me to this page:

![image](https://github.com/furbrain/CircuitPython_CaveBLE/assets/8845664/706005c1-b99f-47b0-a227-e5d555c2b38c)

Anyway, where can I find more info about the SAP6? Is it still open-source?

**Comment by furbrain** [comment]
Hi look for my repo furbrain/ STIC. it's all in there.

Phil

**Comment by romainreignier** [comment]
Oh, very cool!
Actually, I am thinking about building a survey tool myself. I have grabbed a RM3100 and a laser module and was about to start programming an ESP32-C3 but the nRF52840 looks promising too.
I will have a deeper look of your repo, even if I don't know anything about MicroPython.
Thanks

**Comment by furbrain** [comment]
If you use circuit python, then you'll be able to use a few of the
libraries I have written, specifically Circuitpython_rm3100 and
circuitpython_magcal -they are both in my GitHub

Phil

**Comment by furbrain** [comment]
URL fixed
